"""Add marketplace models and update user fields

Revision ID: 48028b63f80d
Revises: c92ac79823b3
Create Date: 2025-11-13 14:34:59.784900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48028b63f80d'
down_revision = 'c92ac79823b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, create new tables if they don't exist
    # Check if tables exist first
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create industries table
    if 'industries' not in existing_tables:
        op.create_table('industries',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('icon_url', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
        op.create_index(op.f('ix_industries_slug'), 'industries', ['slug'], unique=True)
        op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    
    # Create categories table
    if 'categories' not in existing_tables:
        op.create_table('categories',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('icon_url', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
        op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
        op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    
    # Create services table
    if 'services' not in existing_tables:
        op.create_table('services',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('category_id', sa.String(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('endpoint_path', sa.String(), nullable=False),
        sa.Column('request_schema', sa.JSON(), nullable=True),
        sa.Column('response_schema', sa.JSON(), nullable=True),
        sa.Column('price_per_call', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
        op.create_index(op.f('ix_services_slug'), 'services', ['slug'], unique=True)
        op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=False)
    
    # Create service_industries table
    if 'service_industries' not in existing_tables:
        op.create_table('service_industries',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_id', sa.String(), nullable=False),
        sa.Column('industry_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_service_industries_service_id'), 'service_industries', ['service_id'], unique=False)
        op.create_index(op.f('ix_service_industries_industry_id'), 'service_industries', ['industry_id'], unique=False)
    
    # Create subscriptions table
    if 'subscriptions' not in existing_tables:
        op.create_table('subscriptions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('service_id', sa.String(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('credits_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('credits_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
        op.create_index(op.f('ix_subscriptions_service_id'), 'subscriptions', ['service_id'], unique=False)
    
    # Create transactions table
    if 'transactions' not in existing_tables:
        op.create_table('transactions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('credits_purchased', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('payment_method', sa.String(), nullable=True),
        sa.Column('payment_status', sa.String(), nullable=False),
        sa.Column('transaction_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
        op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
        op.create_index(op.f('ix_transactions_transaction_id'), 'transactions', ['transaction_id'], unique=True)
    
    # Now add columns to api_keys - first as nullable, then clean up, then make NOT NULL
    # Check if columns already exist
    api_keys_columns = [col['name'] for col in inspector.get_columns('api_keys')] if 'api_keys' in existing_tables else []
    
    if 'service_id' not in api_keys_columns:
        op.add_column('api_keys', sa.Column('service_id', sa.String(), nullable=True))
    if 'subscription_id' not in api_keys_columns:
        op.add_column('api_keys', sa.Column('subscription_id', sa.String(), nullable=True))
    
    # Delete old api_keys that don't have a service (they'll be recreated with proper service mapping)
    if 'service_id' in api_keys_columns:
        op.execute("DELETE FROM api_keys WHERE service_id IS NULL")
    
    # Now make service_id NOT NULL if it's still nullable
    if 'service_id' in api_keys_columns:
        # Check if it's nullable
        service_id_col = next((col for col in inspector.get_columns('api_keys') if col['name'] == 'service_id'), None)
        if service_id_col and service_id_col.get('nullable', True):
            op.execute("DELETE FROM api_keys WHERE service_id IS NULL")
            op.alter_column('api_keys', 'service_id', nullable=False)
    
    op.create_index(op.f('ix_api_keys_service_id'), 'api_keys', ['service_id'], unique=False)
    op.create_index(op.f('ix_api_keys_subscription_id'), 'api_keys', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'api_keys', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.add_column('api_usage_logs', sa.Column('service_id', sa.String(), nullable=True))
    op.add_column('api_usage_logs', sa.Column('subscription_id', sa.String(), nullable=True))
    op.add_column('api_usage_logs', sa.Column('credits_deducted', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('api_usage_logs', sa.Column('credits_before', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('api_usage_logs', sa.Column('credits_after', sa.Numeric(precision=10, scale=2), nullable=True))
    # Set default for existing records
    op.execute("UPDATE api_usage_logs SET credits_deducted = 1.0 WHERE credits_deducted IS NULL")
    op.alter_column('api_usage_logs', 'credits_deducted', nullable=False)
    op.create_index(op.f('ix_api_usage_logs_service_id'), 'api_usage_logs', ['service_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_subscription_id'), 'api_usage_logs', ['subscription_id'], unique=False)
    op.create_foreign_key(None, 'api_usage_logs', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'api_usage_logs', 'services', ['service_id'], ['id'], ondelete='SET NULL')
    op.add_column('rc_data', sa.Column('is_commercial', sa.String(), nullable=True))
    op.add_column('rc_data', sa.Column('source', sa.String(), nullable=True))
    op.add_column('rc_data', sa.Column('own_json', sa.JSON(), nullable=True))
    op.add_column('rc_data', sa.Column('privahan_json', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('gst_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('msme_certificate', sa.String(), nullable=True))
    op.add_column('users', sa.Column('aadhar_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pan_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('total_credits', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('credits_used', sa.Numeric(precision=10, scale=2), nullable=True))
    # Set defaults for existing users
    op.execute("UPDATE users SET total_credits = 0 WHERE total_credits IS NULL")
    op.execute("UPDATE users SET credits_used = 0 WHERE credits_used IS NULL")
    op.alter_column('users', 'total_credits', nullable=False)
    op.alter_column('users', 'credits_used', nullable=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_column('users', 'credits_used')
    op.drop_column('users', 'total_credits')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'birthday')
    op.drop_column('users', 'pan_number')
    op.drop_column('users', 'aadhar_number')
    op.drop_column('users', 'msme_certificate')
    op.drop_column('users', 'gst_number')
    op.drop_column('users', 'address')
    op.drop_column('users', 'website_link')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'customer_name')
    op.drop_column('rc_data', 'privahan_json')
    op.drop_column('rc_data', 'own_json')
    op.drop_column('rc_data', 'source')
    op.drop_column('rc_data', 'is_commercial')
    op.drop_constraint(None, 'api_usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'api_usage_logs', type_='foreignkey')
    op.drop_index(op.f('ix_api_usage_logs_subscription_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_service_id'), table_name='api_usage_logs')
    op.drop_column('api_usage_logs', 'credits_after')
    op.drop_column('api_usage_logs', 'credits_before')
    op.drop_column('api_usage_logs', 'credits_deducted')
    op.drop_column('api_usage_logs', 'subscription_id')
    op.drop_column('api_usage_logs', 'service_id')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_subscription_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_service_id'), table_name='api_keys')
    op.drop_column('api_keys', 'subscription_id')
    op.drop_column('api_keys', 'service_id')
    # Drop new tables
    op.drop_table('transactions')
    op.drop_table('subscriptions')
    op.drop_table('service_industries')
    op.drop_table('services')
    op.drop_table('categories')
    op.drop_table('industries')
    # ### end Alembic commands ###

