"""Initial migration

Revision ID: c92ac79823b3
Revises: 
Create Date: 2025-11-12 17:22:54.303896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92ac79823b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challan_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vehicle_no', sa.String(), nullable=False),
    sa.Column('total_paid_count', sa.Integer(), nullable=True),
    sa.Column('total_pending_count', sa.Integer(), nullable=True),
    sa.Column('total_physical_court_count', sa.Integer(), nullable=True),
    sa.Column('total_virtual_court_count', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_data_vehicle_no'), 'challan_data', ['vehicle_no'], unique=False)
    op.create_table('external_api_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('api_type', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('auth_type', sa.String(), nullable=True),
    sa.Column('credentials_encrypted', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('licence_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dl_no', sa.String(), nullable=False),
    sa.Column('error_cd', sa.Integer(), nullable=True),
    sa.Column('db_loc', sa.String(), nullable=True),
    sa.Column('bio_bio_id', sa.String(), nullable=True),
    sa.Column('bio_gender', sa.Integer(), nullable=True),
    sa.Column('bio_gender_desc', sa.String(), nullable=True),
    sa.Column('bio_blood_group_name', sa.String(), nullable=True),
    sa.Column('bio_citizen', sa.String(), nullable=True),
    sa.Column('bio_first_name', sa.String(), nullable=True),
    sa.Column('bio_last_name', sa.String(), nullable=True),
    sa.Column('bio_full_name', sa.String(), nullable=True),
    sa.Column('bio_nat_name', sa.String(), nullable=True),
    sa.Column('bio_dependent_relation', sa.String(), nullable=True),
    sa.Column('bio_swd_full_name', sa.String(), nullable=True),
    sa.Column('bio_perm_add1', sa.Text(), nullable=True),
    sa.Column('bio_perm_add2', sa.Text(), nullable=True),
    sa.Column('bio_perm_add3', sa.Text(), nullable=True),
    sa.Column('bio_temp_add1', sa.Text(), nullable=True),
    sa.Column('bio_temp_add2', sa.Text(), nullable=True),
    sa.Column('bio_temp_add3', sa.Text(), nullable=True),
    sa.Column('bio_dob', sa.String(), nullable=True),
    sa.Column('bio_endorsement_no', sa.String(), nullable=True),
    sa.Column('bio_endorse_dt', sa.String(), nullable=True),
    sa.Column('bio_photo_url', sa.String(), nullable=True),
    sa.Column('bio_signature_url', sa.String(), nullable=True),
    sa.Column('dl_status', sa.String(), nullable=True),
    sa.Column('dl_issue_dt', sa.String(), nullable=True),
    sa.Column('dl_nt_valdfr_dt', sa.String(), nullable=True),
    sa.Column('dl_nt_valdto_dt', sa.String(), nullable=True),
    sa.Column('dl_remarks', sa.Text(), nullable=True),
    sa.Column('ola_code', sa.String(), nullable=True),
    sa.Column('ola_name', sa.String(), nullable=True),
    sa.Column('state_cd', sa.String(), nullable=True),
    sa.Column('rto_code', sa.String(), nullable=True),
    sa.Column('om_rto_fullname', sa.String(), nullable=True),
    sa.Column('om_office_townname', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licence_data_bio_first_name'), 'licence_data', ['bio_first_name'], unique=False)
    op.create_index(op.f('ix_licence_data_bio_full_name'), 'licence_data', ['bio_full_name'], unique=False)
    op.create_index(op.f('ix_licence_data_bio_last_name'), 'licence_data', ['bio_last_name'], unique=False)
    op.create_index(op.f('ix_licence_data_dl_no'), 'licence_data', ['dl_no'], unique=True)
    op.create_table('pricing_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('api_calls_limit', sa.Integer(), nullable=True),
    sa.Column('price_per_call', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('monthly_fee', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rc_data',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('vi_status', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('rto', sa.String(), nullable=True),
    sa.Column('rto_code', sa.String(), nullable=True),
    sa.Column('reg_date', sa.String(), nullable=True),
    sa.Column('chassis_no', sa.String(), nullable=True),
    sa.Column('engine_no', sa.String(), nullable=True),
    sa.Column('vehicle_class', sa.String(), nullable=True),
    sa.Column('vehicle_category', sa.String(), nullable=True),
    sa.Column('vehicle_color', sa.String(), nullable=True),
    sa.Column('maker', sa.String(), nullable=True),
    sa.Column('maker_modal', sa.String(), nullable=True),
    sa.Column('body_type_desc', sa.String(), nullable=True),
    sa.Column('fuel_type', sa.String(), nullable=True),
    sa.Column('fuel_norms', sa.String(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('present_address', sa.Text(), nullable=True),
    sa.Column('mobile_no', sa.String(), nullable=True),
    sa.Column('owner_sr_no', sa.Integer(), nullable=True),
    sa.Column('fitness_upto', sa.String(), nullable=True),
    sa.Column('tax_upto', sa.String(), nullable=True),
    sa.Column('ins_company', sa.String(), nullable=True),
    sa.Column('ins_upto', sa.String(), nullable=True),
    sa.Column('policy_no', sa.String(), nullable=True),
    sa.Column('puc_no', sa.String(), nullable=True),
    sa.Column('puc_upto', sa.String(), nullable=True),
    sa.Column('manufactured_month_year', sa.String(), nullable=True),
    sa.Column('unladen_weight', sa.Integer(), nullable=True),
    sa.Column('vehicle_gross_weight', sa.Integer(), nullable=True),
    sa.Column('no_cylinders', sa.Integer(), nullable=True),
    sa.Column('cubic_cap', sa.Integer(), nullable=True),
    sa.Column('no_of_seats', sa.Integer(), nullable=True),
    sa.Column('sleeper_cap', sa.Integer(), nullable=True),
    sa.Column('stand_cap', sa.Integer(), nullable=True),
    sa.Column('wheel_base', sa.Integer(), nullable=True),
    sa.Column('national_permit_upto', sa.String(), nullable=True),
    sa.Column('national_permit_no', sa.String(), nullable=True),
    sa.Column('national_permit_issued_by', sa.String(), nullable=True),
    sa.Column('permit_no', sa.String(), nullable=True),
    sa.Column('permit_issue_date', sa.String(), nullable=True),
    sa.Column('permit_from', sa.String(), nullable=True),
    sa.Column('permit_upto', sa.String(), nullable=True),
    sa.Column('permit_type', sa.String(), nullable=True),
    sa.Column('financer_details', sa.String(), nullable=True),
    sa.Column('blacklist_status', sa.String(), nullable=True),
    sa.Column('noc_details', sa.String(), nullable=True),
    sa.Column('status_on', sa.String(), nullable=True),
    sa.Column('non_use_status', sa.String(), nullable=True),
    sa.Column('non_use_from', sa.String(), nullable=True),
    sa.Column('non_use_to', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rc_data_owner_name'), 'rc_data', ['owner_name'], unique=False)
    op.create_index(op.f('ix_rc_data_reg_no'), 'rc_data', ['reg_no'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='apikeystatus'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_type', sa.Enum('ACCESS', 'REFRESH', name='tokentype'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_table('challan_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challan_data_id', sa.String(), nullable=False),
    sa.Column('reg_no', sa.String(), nullable=False),
    sa.Column('violator_name', sa.String(), nullable=True),
    sa.Column('dl_rc_no', sa.String(), nullable=True),
    sa.Column('challan_no', sa.String(), nullable=False),
    sa.Column('challan_date', sa.String(), nullable=True),
    sa.Column('challan_amount', sa.Integer(), nullable=True),
    sa.Column('challan_status', sa.String(), nullable=True),
    sa.Column('challan_payment_date', sa.String(), nullable=True),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('payment_source', sa.String(), nullable=True),
    sa.Column('challan_url', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('payment_url', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('dpt_cd', sa.Integer(), nullable=True),
    sa.Column('rto_cd', sa.Integer(), nullable=True),
    sa.Column('court_name', sa.String(), nullable=True),
    sa.Column('court_address', sa.Text(), nullable=True),
    sa.Column('sent_to_court_on', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('traffic_police', sa.Integer(), nullable=True),
    sa.Column('vehicle_impound', sa.String(), nullable=True),
    sa.Column('office_name', sa.String(), nullable=True),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('office_text', sa.String(), nullable=True),
    sa.Column('virtual_court_status', sa.Integer(), nullable=True),
    sa.Column('court_status', sa.Integer(), nullable=True),
    sa.Column('valid_contact_no', sa.Integer(), nullable=True),
    sa.Column('payment_eligible', sa.Integer(), nullable=True),
    sa.Column('status_txt', sa.Text(), nullable=True),
    sa.Column('payment_gateway', sa.Integer(), nullable=True),
    sa.Column('status_desc', sa.Text(), nullable=True),
    sa.Column('physical_challan', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challan_data_id'], ['challan_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challan_records_challan_no'), 'challan_records', ['challan_no'], unique=True)
    op.create_index(op.f('ix_challan_records_reg_no'), 'challan_records', ['reg_no'], unique=False)
    op.create_index(op.f('ix_challan_records_violator_name'), 'challan_records', ['violator_name'], unique=False)
    op.create_table('licence_coverages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('licence_id', sa.String(), nullable=False),
    sa.Column('dl_no', sa.String(), nullable=False),
    sa.Column('cov_cd', sa.Integer(), nullable=True),
    sa.Column('cov_desc', sa.String(), nullable=True),
    sa.Column('cov_abbrv', sa.String(), nullable=True),
    sa.Column('cov_status', sa.String(), nullable=True),
    sa.Column('vec_catg', sa.String(), nullable=True),
    sa.Column('issue_dt', sa.String(), nullable=True),
    sa.Column('endorse_dt', sa.String(), nullable=True),
    sa.Column('ola_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['licence_id'], ['licence_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_licence_coverages_dl_no'), 'licence_coverages', ['dl_no'], unique=False)
    op.create_table('api_usage_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=True),
    sa.Column('endpoint_type', sa.String(), nullable=False),
    sa.Column('request_params', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_usage_logs_api_key_id'), 'api_usage_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_created_at'), 'api_usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_user_id'), 'api_usage_logs', ['user_id'], unique=False)
    op.create_table('challan_offences',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('challan_record_id', sa.String(), nullable=False),
    sa.Column('offence_name', sa.Text(), nullable=True),
    sa.Column('mva', sa.Text(), nullable=True),
    sa.Column('penalty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['challan_record_id'], ['challan_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('challan_offences')
    op.drop_index(op.f('ix_api_usage_logs_user_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_created_at'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_api_key_id'), table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    op.drop_index(op.f('ix_licence_coverages_dl_no'), table_name='licence_coverages')
    op.drop_table('licence_coverages')
    op.drop_index(op.f('ix_challan_records_violator_name'), table_name='challan_records')
    op.drop_index(op.f('ix_challan_records_reg_no'), table_name='challan_records')
    op.drop_index(op.f('ix_challan_records_challan_no'), table_name='challan_records')
    op.drop_table('challan_records')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_rc_data_reg_no'), table_name='rc_data')
    op.drop_index(op.f('ix_rc_data_owner_name'), table_name='rc_data')
    op.drop_table('rc_data')
    op.drop_table('pricing_plans')
    op.drop_index(op.f('ix_licence_data_dl_no'), table_name='licence_data')
    op.drop_index(op.f('ix_licence_data_bio_last_name'), table_name='licence_data')
    op.drop_index(op.f('ix_licence_data_bio_full_name'), table_name='licence_data')
    op.drop_index(op.f('ix_licence_data_bio_first_name'), table_name='licence_data')
    op.drop_table('licence_data')
    op.drop_table('external_api_configs')
    op.drop_index(op.f('ix_challan_data_vehicle_no'), table_name='challan_data')
    op.drop_table('challan_data')
    # ### end Alembic commands ###

