"""remove_subscriptions_add_service_access

Revision ID: fb14a29d7d0f
Revises: encrypted_key_001
Create Date: 2025-11-25 12:42:59.063447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb14a29d7d0f'
down_revision = 'encrypted_key_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create user_service_access table first (if it doesn't exist)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'user_service_access' not in tables:
        op.create_table('user_service_access',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('service_id', sa.VARCHAR(), nullable=False),
    sa.Column('granted_by', sa.VARCHAR(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_service_access_user_id'), 'user_service_access', ['user_id'], unique=False)
        op.create_index(op.f('ix_user_service_access_service_id'), 'user_service_access', ['service_id'], unique=False)
    
    # Remove subscription-related tables and columns
    # Drop foreign keys first, then columns, then table
    op.drop_index('ix_api_keys_subscription_id', table_name='api_keys')
    op.drop_constraint('api_keys_subscription_id_fkey', 'api_keys', type_='foreignkey')
    op.drop_column('api_keys', 'subscription_id')
    op.drop_index('ix_api_usage_logs_subscription_id', table_name='api_usage_logs')
    op.drop_constraint('api_usage_logs_subscription_id_fkey', 'api_usage_logs', type_='foreignkey')
    op.drop_column('api_usage_logs', 'subscription_id')
    op.drop_index('ix_subscriptions_service_id', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate subscription-related tables and columns
    op.add_column('api_usage_logs', sa.Column('subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('api_usage_logs_subscription_id_fkey', 'api_usage_logs', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_api_usage_logs_subscription_id', 'api_usage_logs', ['subscription_id'], unique=False)
    op.add_column('api_keys', sa.Column('subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('api_keys_subscription_id_fkey', 'api_keys', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_api_keys_subscription_id', 'api_keys', ['subscription_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus'), autoincrement=False, nullable=False),
    sa.Column('credits_allocated', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('credits_remaining', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='subscriptions_service_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_service_id', 'subscriptions', ['service_id'], unique=False)
    
    # Drop user_service_access table
    op.drop_index(op.f('ix_user_service_access_service_id'), table_name='user_service_access')
    op.drop_index(op.f('ix_user_service_access_user_id'), table_name='user_service_access')
    op.drop_table('user_service_access')
    # ### end Alembic commands ###

